### ISSUE TITLE
ImportError: No module named core.script

### ISSUE THREAD

**Issue by savetree** [alecalve/python-bitcoin-blockchain-parser#25]
Hi. Wile trying to run example from README I get following error.
How can I fix this?

```
# python test.py /root/.bitcoin/blocks/
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from blockchain_parser.blockchain import Blockchain
  File "build/bdist.linux-x86_64/egg/blockchain_parser/blockchain.py", line 16, in <module>
  File "build/bdist.linux-x86_64/egg/blockchain_parser/block.py", line 12, in <module>
  File "build/bdist.linux-x86_64/egg/blockchain_parser/transaction.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/blockchain_parser/input.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/blockchain_parser/script.py", line 12, in <module>
ImportError: No module named core.script
```

**Comment by alecalve** [comment]
Which version of Python are you running? This project is designed to work with Python3.
