### ISSUE TITLE
bitcoin.core.script.CScriptTruncatedPushDataError: PUSHDATA(75): truncated data

### ISSUE THREAD

**Issue by pngingg** [alecalve/python-bitcoin-blockchain-parser#71]
Thanks for your project. But when I parse blk01400.dat, an error ocurred. How can I fix it?
```
Traceback (most recent call last):
  File "test_code.py", line 20, in <module>
    print("tx=%s outputno=%d type=%s value=%s" % (tx.hash, no, output.type, output.value))
  File "/usr/local/lib/python3.5/dist-packages/blockchain_parser-0.1.4-py3.5.egg/blockchain_parser/output.py", line 101, in type
    if self.is_pubkey():
  File "/usr/local/lib/python3.5/dist-packages/blockchain_parser-0.1.4-py3.5.egg/blockchain_parser/output.py", line 84, in is_pubkey
    return self.script.is_pubkey()
  File "/usr/local/lib/python3.5/dist-packages/blockchain_parser-0.1.4-py3.5.egg/blockchain_parser/script.py", line 102, in is_pubkey
    return len(self.operations) == 2 \
  File "/usr/local/lib/python3.5/dist-packages/blockchain_parser-0.1.4-py3.5.egg/blockchain_parser/script.py", line 73, in operations
    self._operations = list(self.script)
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/script.py", line 628, in __iter__
    for (opcode, data, sop_idx) in self.raw_iter():
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/script.py", line 613, in raw_iter
    raise CScriptTruncatedPushDataError('%s: truncated data' % pushdata_type, data)
bitcoin.core.script.CScriptTruncatedPushDataError: PUSHDATA(75): truncated data
```

**Comment by pngingg** [comment]
btw, can it parse addresses start with "bc1"?

**Comment by alecalve** [comment]
bech32 is not supported _yet_.

**Comment by Subcode** [comment]
I'm getting this same error, is there a way to fix this or bypass it?
