### ISSUE TITLE
running ./tests.sh results in KeyError: 'BREAK_LOOP'

### ISSUE THREAD

**Issue by schumannd** [alecalve/python-bitcoin-blockchain-parser#89]
This seems to happen within the coverage module on import.

Also the `npm i` step is missing from the readme.

**Comment by alecalve** [comment]
Hum, never seen this before.

I've updated the README and added a developing section. Does it still occur if you follow it?

**Comment by schumannd** [comment]
Nope didn't change anything:

Traceback (most recent call last):
  File "/Users/user1/.virtualenvs/test/bin/coverage", line 5, in <module>
    from coverage.cmdline import main
  File "/Users/user1/.virtualenvs/test/lib/python3.8/site-packages/coverage/__init__.py", line 13, in <module>
    from coverage.control import Coverage, process_startup
  File "/Users/user1/.virtualenvs/test/lib/python3.8/site-packages/coverage/control.py", line 30, in <module>
    from coverage.python import PythonFileReporter
  File "/Users/user1/.virtualenvs/test/lib/python3.8/site-packages/coverage/python.py", line 11, in <module>
    from coverage.parser import PythonParser
  File "/Users/user1/.virtualenvs/test/lib/python3.8/site-packages/coverage/parser.py", line 320, in <module>
    OP_BREAK_LOOP = _opcode('BREAK_LOOP')
  File "/Users/user1/.virtualenvs/test/lib/python3.8/site-packages/coverage/parser.py", line 278, in _opcode
    return dis.opmap[name]
KeyError: 'BREAK_LOOP'

**Comment by sjorsvanheuveln** [comment]
Getting the same error.

**Comment by alecalve** [comment]
Updating the coverage library fixed this for me.
