### ISSUE TITLE
I/O Error when calling get_ordered_blocks

### ISSUE THREAD

**Issue by raven4752** [alecalve/python-bitcoin-blockchain-parser#92]
Hi, When I call get_ordered_blocks, i got the following exception:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: b'IO error: /mnt/f/bitcoin/blocks/index: Input/output error'

My code looks like:

```
  from blockchain_parser.blockchain import Blockchain
  import os
  blockchain = Blockchain(os.path.expanduser(r'/mnt/f/bitcoin/blocks'))
  for block in blockchain.get_ordered_blocks(os.path.expanduser('/mnt/f/bitcoin/blocks/index'), end=1000):
       print("height=%d block=%s" % (block.height, block.hash))
```

No bitcoin core is running.  blockchain-parser version is 1.2.0.  python-bitcoinlib version is 0.11.0 plyvel version is 1.2.0. I tried to run in windows sub system. 
The stack trace does not provides much information. Is there anything wrong with my code?
Thanks in advance.

**Comment by raven4752** [comment]
the problem disappears when i reinstall plyvel.
